image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

before_script:
  # Install dependencies inside a Docker container that has Python and Docker installed
  - apk update && apk add --no-cache python3 py3-pip
  - python3 -m venv venv  
  - . venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Building the application..."

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - docker build -t django-app -t imranahmad786/django-app:latest .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - docker push imranahmad786/django-app:latest
