version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:  
      - checkout
      - setup_remote_docker:
          docker_layer_chaching: false
      - run:
          name: Build Docker Image
          command: |
            docker build -t django-app -t imranahmad786/django-app:latest .
            echo $DOCKER_PASSWORD | docker login -u imranahmad786 --password-stdin
            docker push imranahmad786/django-app:latest 
workflows:
  build_and_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main
