version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Set up Environment
          command: |
            python -m venv venv  # Create a virtual environment
            . venv/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies

  # Comment out or remove the test job
  # test:
  #   docker:
  #     - image: cimg/python:3.11
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run Tests
  #         command: |
  #           . venv/bin/activate
  #           python manage.py test

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deploy Application
          command: echo "Deploying to production server"  # Replace with your deployment commands

workflows:
  build_and_deploy:
    jobs:
      - build
      # Skip the test job by commenting out
      # - test:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build  # Directly depend on the build job
          filters:
            branches:
              only: main
