version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup_remote_docker:
          version: 20.10.7  # Specify Docker version if needed
      - run:
          name: Build Docker Image
          command: docker build -t django-app .
      - run:
          name: Run Docker Container
          command: docker run -d -p 8000:8000 django-app

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
