version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Use a Docker image with Python 3.11
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Set up Environment
          command: |
            python -m venv venv  # Create a virtual environment
            . venv/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies

  test:
    docker:
      - image: cimg/python:3.11  # Same Docker image for consistency
    steps:
      - checkout  # Check out the code
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate  # Activate the virtual environment
            python manage.py test  # Run Django tests

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deploy Application
          command: echo "Deploying to production server"  # Replace with your deployment commands

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main  # Only deploy from the main branch
